services:

  swift-token-server:
    image: everyday-ai/swift-token-server:v0.3.2-dev
    container_name: swift-token-server
    env_file:
      - ./swift-token-server/.env
    ports:
      - "82:8080"
    restart: unless-stopped

  swift-swagger-ui:
    image: everyday-ai/swift-swagger-ui:v1.1.0-dev
    container_name: swift-swagger-ui
    ports:
      - "83:8080"
    restart: unless-stopped

  swift-ui-client:
    image: everyday-ai/swift-ui-client:v0.1.0-dev
    container_name: swift-ui-client
    environment:
      - PROXY_BASE_URL=http://swift-token-server:8080/proxy
      - TOKEN_SERVER_URL=http://swift-token-server:8080
      - SWAGGER_UI_URL=http://swift-swagger-ui:8080
    ports:
      - "84:8080"
    depends_on:
      - swift-token-server
    restart: unless-stopped
